export class LineDetailsVm {
    ExternalToken: string;
    DN_NO: string
    PORT_TYPE: string
    VOICE_STATUS: string
    DATA_STATUS: string
    OPERATOR_ID: string
    ISP_ID: string
    MSAN_IP: string
    MSAN_VENDORID: string
    MSAN_VENDOR: string
    MSAN_CODE: string
    FRAME: string
    SHELF: string
    VOICE_SLOT: string
    VOICE_PORT: string
    DATA_SLOT: string
    DATA_PORT: string
    ONT_ID: string
    USER_TYPE: string
    EMS_ID: string
    SERVICE_ID: string
    EXCHANGE_NAME: string
    MSAN_HOSTNAME: string
    SPEED_PROFILE: string
    NPID: string
    ONT_ONU_SERIAL_NO: string
    ONT_ONU_MODEL: string
    CPE_TYPE: string
    DEFAULT_OUTER_VLAN: string
    DEFAULT_INNER_VLAN: string
    INNER_VLAN: string
    OUTER_VLAN: string
    USER_VLAN: string
    NEW_INNER_VLAN: string
    NEW_OUTER_VLAN: string
    GATEWAY_IP: string
    OPTMIZE_LINE: string
    MASK: string
    PROXY_IP: string
    PROXY_PORT: string
    SECPROXY_IP: string
    ONT_SIGNALING_IP: string
    ONT_SIGNALING_PORT: string
    CONFIG_FILE: string
    STATUS: string
    RESULT_CODE: string
    RESULT_MESSAGE: string
    ROWVERSION: string
}